# Generated by Django 4.2 on 2023-04-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('attack_type', models.CharField(max_length=50)),
                ('damage', models.IntegerField(verbose_name='')),
                ('base_attack_time', models.FloatField(verbose_name='')),
                ('attack_range', models.IntegerField(verbose_name='')),
                ('main_attribute', models.TextField(max_length=15)),
                ('attribute_agi', models.CharField(max_length=50)),
                ('attribute_str', models.CharField(max_length=50)),
                ('attribute_int', models.CharField(max_length=50)),
                ('mana_regen', models.FloatField(verbose_name='')),
                ('hp_regen', models.FloatField(verbose_name='')),
                ('armor', models.IntegerField(verbose_name='')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
