# Generated by Django 4.2 on 2023-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=50)),
                ('active', models.CharField(max_length=200)),
                ('passive', models.CharField(max_length=200)),
                ('stats', models.CharField(max_length=100)),
                ('price', models.IntegerField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='neutral_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('active', models.CharField(max_length=200)),
                ('passive', models.CharField(max_length=200)),
                ('stats', models.CharField(max_length=100)),
                ('tier', models.IntegerField(verbose_name='')),
            ],
        ),
    ]
