# Generated by Django 4.2 on 2023-05-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_items_neutral_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ancient_neutral_camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('health', models.IntegerField(verbose_name='')),
                ('health_regen', models.FloatField(verbose_name='')),
                ('mana', models.IntegerField(verbose_name='')),
                ('mana_regen', models.FloatField(verbose_name='')),
                ('gold_bounty', models.CharField(max_length=10)),
                ('XP_bounty', models.CharField(max_length=10)),
                ('armor', models.FloatField(verbose_name='')),
                ('magic_resist', models.CharField(max_length=10)),
                ('attack_speed', models.FloatField(verbose_name='')),
                ('attack_range', models.IntegerField(verbose_name='')),
                ('damage', models.IntegerField(verbose_name='')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='big_neutral_camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('health', models.IntegerField(verbose_name='')),
                ('health_regen', models.FloatField(verbose_name='')),
                ('mana', models.IntegerField(verbose_name='')),
                ('mana_regen', models.FloatField(verbose_name='')),
                ('gold_bounty', models.CharField(max_length=10)),
                ('XP_bounty', models.CharField(max_length=10)),
                ('armor', models.FloatField(verbose_name='')),
                ('magic_resist', models.CharField(max_length=10)),
                ('attack_speed', models.FloatField(verbose_name='')),
                ('attack_range', models.IntegerField(verbose_name='')),
                ('damage', models.IntegerField(verbose_name='')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='line_creeps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack_type', models.CharField(max_length=50)),
                ('damage', models.IntegerField(verbose_name='')),
                ('attack_time', models.FloatField(verbose_name='')),
                ('attack_range', models.IntegerField(verbose_name='')),
                ('move_speed', models.IntegerField(verbose_name='')),
                ('armor', models.FloatField(verbose_name='')),
                ('magic_resist', models.CharField(max_length=10)),
                ('health', models.IntegerField(verbose_name='')),
                ('mana', models.IntegerField(verbose_name='')),
                ('health_regen', models.FloatField(verbose_name='')),
                ('mana_regen', models.FloatField(verbose_name='')),
                ('gold_bounty', models.CharField(max_length=10)),
                ('XP_bounty', models.CharField(max_length=10)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='small_neutral_camps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('health', models.IntegerField(verbose_name='')),
                ('health_regen', models.FloatField(verbose_name='')),
                ('mana', models.IntegerField(verbose_name='')),
                ('mana_regen', models.FloatField(verbose_name='')),
                ('gold_bounty', models.CharField(max_length=10)),
                ('XP_bounty', models.CharField(max_length=10)),
                ('armor', models.FloatField(verbose_name='')),
                ('magic_resist', models.CharField(max_length=10)),
                ('attack_speed', models.FloatField(verbose_name='')),
                ('attack_range', models.IntegerField(verbose_name='')),
                ('damage', models.IntegerField(verbose_name='')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='structures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('health', models.IntegerField(verbose_name='')),
                ('health_regen', models.FloatField(verbose_name='')),
                ('gold_bounty', models.CharField(max_length=10)),
                ('armor', models.FloatField(verbose_name='')),
                ('magic_resist', models.CharField(max_length=10)),
                ('attack_speed', models.FloatField(verbose_name='')),
                ('damage', models.IntegerField(verbose_name='')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
